---
title: Análise Exploratório sobre Mortalidade por Psicoativos no Brasil e no Espírito
  Santo
author: "Caroline de Oliveira, Franco Lovatti e Iane Martins"
date: "2024-07-14"
output: html_document
---


```{r setup, warning = FALSE, message=FALSE, echo=FALSE, include=FALSE}
library(readr)
library(plotly)
library(dplyr)
library(data.table)
library(lubridate)
library(ggplot2)
library(RColorBrewer)
library(reactR)
library(htmltools)
library(reactable)
library(stringr)
library(sidrar)
```


```{r, warning = FALSE, message=FALSE, echo=FALSE, include=FALSE}

setwd("DaSLab/Psicoativos/ANALISE_EXPLORATORIA_1")


# Leitura e combinação dos dados de 2013 a 2022
dados_br_total <- c()

for (ano in 2013:2022) {
  df <- readRDS(paste0("base_de_dados/dados_", ano, ".rds"))
  dados_br_total <- bind_rows(df, dados_br_total)
}

# Adicionando colunas extras
dados_br_total$DTOBITO <- ymd(dados_br_total$DTOBITO)
dados_br_total$ANOOBITO <- year(dados_br_total$DTOBITO)

dados_br_total$DTNASC <- ymd(dados_br_total$DTNASC)
dados_br_total$DTOBITO <- ymd(dados_br_total$DTOBITO)
dados_br_total$IDADE2 <- floor(interval(start = dados_br_total$DTNASC, end = dados_br_total$DTOBITO) / years(1))

# Carregar e adicionar códigos UF
var_extras_UF <- read_table("bases_de_dados_externas/var_extras_UF.txt")
var_extras_UF$codigoUF <- as.character(var_extras_UF$codigoUF)

dados_br_total <- dados_br_total %>%
  mutate(codigoUF = substr(as.character(CODMUNOCOR), 1, 2))

dados_br_total <- inner_join(dados_br_total, var_extras_UF, by = "codigoUF")

# Filtrar dados do ES
dados_es_total <- dados_br_total %>%
  filter(Sigla == "ES")

# Filtrar dados por psicoativos (código F1)
dados_br_psic <- dados_br_total[grepl("F1", dados_br_total$CAUSABAS, ignore.case = TRUE),]
dados_es_psic <- dados_es_total[grepl("F1", dados_es_total$CAUSABAS, ignore.case = TRUE),]






```









```{r, warning = FALSE, message=FALSE, echo=FALSE, include=FALSE}
source("CODIGOS/preparacao_dos_dados/leitura_filtragem_02.R")
source("CODIGOS/analise_carol.R")
library(gridExtra)
```

```{r fig.width=12, fig.height=6, echo=FALSE}
grid.arrange(boxplot.anoidad.es, boxplot.anoidad.es.psic, ncol=2)
```
