---
title: Análise Exploratório sobre Mortalidade por Psicoativos no Brasil e no Espírito
  Santo
author: "Caroline de Oliveira, Franco Lovatti e Iane Martins"
date: "2024-07-14"
output: html_document
---


```{r setup, warning = FALSE, message=FALSE, echo=FALSE, include=FALSE}
library(readr)
library(plotly)
library(dplyr)
library(data.table)
library(lubridate)
library(ggplot2)
library(RColorBrewer)
library(reactR)
library(htmltools)
library(reactable)
library(stringr)
library(sidrar)

knitr::opts_chunk$set(echo = TRUE)

dados_br_total <- readRDS("Psicoativos/NÁLISE EXPLORATÓRIA 1/dados_br_total.rds")
dados_es_total <- readRDS("Psicoativos/NÁLISE EXPLORATÓRIA 1/dados_es_total.rds")
dados_br_psic <- readRDS("Psicoativos/NÁLISE EXPLORATÓRIA 1/dados_br_psic.rds")
dados_es_psic <- readRDS("Psicoativos/NÁLISE EXPLORATÓRIA 1/dados_es_psic.rds")

```


```{r, warning = FALSE, message=FALSE, echo=FALSE, include=FALSE}
source("analise.carol.R")
library(gridExtra)
```

```{r fig.width=12, fig.height=6, echo=FALSE}
grid.arrange(boxplot.anoidad.es, boxplot.anoidad.es.psic, ncol=2)
```
