---
title: Análise Exploratório sobre Mortalidade por Psicoativos no Brasil e no Espírito
  Santo
author: "Caroline de Oliveira, Franco Lovatti e Iane Martins"
date: "2024-07-14"
output: html_document
---


```{r setup, warning = FALSE, message=FALSE, echo=FALSE, include=FALSE}
library(readr)
library(plotly)
library(dplyr)
library(data.table)
library(lubridate)
library(ggplot2)
library(RColorBrewer)
library(reactR)
library(htmltools)
library(reactable)
library(stringr)
library(sidrar)

#FILTRANDO OS DADOS

dados_br_total <- list()

for (ano in 2013:2022) {
  
  if (file.exists(paste0("./base_de_dados/dados_",ano,".rds"))) {
    df <- readRDS(paste0("./base_de_dados/dados_",ano,".rds"))
    dados_br_total <- bind_rows(df, dados_br_total)
  } else {
    stop(paste("Arquivo não encontrado:", caminho))
  }
}

# criar coluna do ano em que o obito ocorreu
dados_br_total$DTOBITO <- ymd(dados_br_total$DTOBITO)
dados_br_total$ANOOBITO <- year(dados_br_total$DTOBITO)

# criar coluna da idade em anos completos
dados_br_total$DTNASC  <- ymd(dados_br_total$DTNASC)
dados_br_total$DTOBITO  <- ymd(dados_br_total$DTOBITO)
dados_br_total$IDADE2  <- floor(interval(start = dados_br_total$DTNASC, end = dados_br_total$DTOBITO) / years(1))

# codigos UF
var_extras_UF <- read_table("./bases_de_dados_externas/var_extras_UF.txt")
var_extras_UF$codigoUF <- as.character(var_extras_UF$codigoUF)

# criando a var codigosUF
dados_br_total <- dados_br_total %>%
  mutate(codigoUF = substr(as.character(CODMUNOCOR), 1, 2))

dados_br_total <- inner_join(dados_br_total, var_extras_UF, by = "codigoUF")

dados_es_total <- dados_br_total %>%
  filter(Sigla == "ES")

# BR PSIC
dados_br_psic <- dados_br_total[grepl("F1", dados_br_total$CAUSABAS, ignore.case = TRUE), ]

# ES PSIC
dados_es_psic <- dados_es_total[grepl("F1", dados_es_total$CAUSABAS, ignore.case = TRUE), ]

```

```{r, warning = FALSE, message=FALSE, echo=FALSE, include=FALSE}
source("./CODIGOS/baixar_pop_13a21")
source("./CODIGOS/grafico_calor_iane")
source("./CODIGOS/genero_raca_escolaridade/escolaridade.R")
source("./CODIGOS/genero_raca_escolaridade/genero.R")
source("./CODIGOS/genero_raca_escolaridade/raca.R")
library(gridExtra)
```

```{r fig.width=12, fig.height=6, echo=FALSE}
grid.arrange(hist_escolaridade_br_total, hist_escolaridade_br_psic, ncol=2)
```
